version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # 開発環境用ポート
    volumes:
      - .:/app # ソースコードをマウント
      - /app/node_modules # node_modulesはコンテナ内で管理
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # ホットリロード用
    command: npm run dev # 開発用コマンド
    restart: unless-stopped
